#!/usr/bin/env sh
action=$1
tag=bingecraft-net/wavy-bacon/devcontainer
if [ "$1" = "build" ] ; then
  docker build -t $tag .
elif [ "$1" = "run" ] ; then
  docker run -it --rm \
    -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
    -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
    -v $HOME/.gitconfig:/root/.gitconfig:ro \
    $tag
else
  echo "usage: $0 build|run"
  exit 1
fi
