#!/usr/bin/env zsh

set -e

podman build -t wavy-bacon .

mkdir -p backups/wavy-bacon
podman run -dip 25565:25565 -v $(pwd)/backups/wavy-bacon:/home/minecraft/backups:U wavy-bacon > cidfile
podman logs --follow $(cat cidfile)
