#!/usr/bin/env zsh

set -e

if [ -f cidfile ] ; then
  podman start $(cat cidfile)
else
  IMAGE_TAG=wavy-bacon

  mkdir -p backups

  podman build -t $IMAGE_TAG .
  podman run -di -p 25565:25565 -p 8100:8100 -v $(readlink -f backups):/home/minecraft/backups:U $IMAGE_TAG > cidfile
fi

podman logs --follow $(cat cidfile)
